name: Auto-Cancel
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize
      - ready_for_review

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      # See https://github.com/marketplace/actions/cancel-workflow-action#advanced
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          workflow_id: e2e-tests-wp-4-7.yml,e2e-tests-wp-4-9-gutenberg.yml,e2e-tests-wp-latest.yml,e2e-tests-wp-nightly.yml,storybook.yml,visual-regression.yml,zips.yml
          access_token: ${{ github.token }}