name: WordPress 4.7
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-20.04
    # if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
      - name: Load Composer cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          path: ~/.cache/composer/files
      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --no-progress
      - name: Load NPM cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
      - name: Build assets
        uses: ./.github/actions/npm
        with:
          command: build:test
      - name: Start MySQL service
        run: |
          sudo systemctl start mysql.service
          sleep 1m
          echo "show databases" | mysql -uroot -proot -h mysql
      - name: Start E2E environment
        run: npm run env:start
        env:
          WP_VERSION: 4.7.19
          AMP_VERSION: 1.5.5
      - name: Run E2E Tests
        run: npm run test:e2e:ci
      - name: Stop E2e environment
        run: npm run env:stop
