name: WordPress Latest
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    # if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          path: ~/.cache/composer/files
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/npm
        with:
          command: build:test
