name: WordPress 4.7
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
env:
  E2E: "1"
  WP_VERSION: "4.7.19"
  AMP_VERSION: "1.5.5"
jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    # if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
      - name: Load Composer cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          path: ~/.cache/composer/files
      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --no-progress
      - name: Load NPM cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
      - name: Build assets
        uses: ./.github/actions/npm
        with:
          command: build:test
      - name: Start E2E environment
        # uses: ./.github/actions/e2e-env
        run: npm run env:start
      - name: Run E2E Tests
        run: npm run test:e2e
      - name: Stop E2E environment
        run: npm run env:stop
