name: WordPress 4.7
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-20.04
    # if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
      - name: Load Composer cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          path: ~/.cache/composer/files
      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --no-progress
      - name: Load NPM cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
      - name: Build assets
        uses: ./.github/actions/npm
        with:
          command: build:test
      - name: Start E2E environment
        uses: ./.github/actions/e2e-env
        with:
          version: 4.7.19
          amp: 1.5.5
      - name: Run E2E Tests
        uses: ./.github/actions/npm
        with:
          command: test:e2e -- tests/e2e/specs/amp/admin-bar.test.js
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: e2e-screenshots
          path: |
            tests/e2e/screenshots
