name: PHP Tests

on:
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

services:
  mysql:
    image: mysql:5.7
    env:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: wordpress
  ports:
    - 3306
  options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

jobs:
  php-tests:
    name: Run PHP Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Composer Install
        run: docker run --rm -v "$PWD:/app" -v "${{ steps.composer-cache.outputs.dir }}:/tmp/cache" composer install --no-interaction --no-progress
      - name: Set up PHP test data
        run: tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      - name: Run Unit Tests
        run: composer test
