name: remove-pr

on:
  pull_request:
    types: [closed]
jobs:
  remove-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      run: |
        bash .github/remove-from-wiki.sh
      env:
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        GIT_REF: ${{ github.ref }}
