name: Visual Regression Testing

on:
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  visual-regression:
    name: Run VR Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
      - name: Load NPM cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run VR tests
        uses: ./.github/actions/npm
        with:
          command: test:visualtest
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: vrt-report
          path: |
            tests/backstop/html_report
            tests/backstop/reference
            tests/backstop/tests
