name: WP 4.9

on:
  - push

jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: wordpress_test
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=3
      wordpress:
        image: wordpress:4.9
        ports:
          - 9002:80
        volumes:
          - wordpress_data:/var/www/html
        env:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_PASSWORD: example
          ABSPATH: /usr/src/wordpress/
          WORDPRESS_DEBUG: 1
          WORDPRESS_CONFIG_EXTRA: |
            define( 'SCRIPT_DEBUG', true );
        options: >-
          --mount type=bind,source=/home/runner/work/site-kit-wp/site-kit-wp,target=/var/www/html/wp-content/plugins/google-site-kit,readonly
        # --mount type=bind,source=/home/runner/work/site-kit-wp/site-kit-wp/tests/e2e/plugins,target=/var/www/html/wp-content/plugins/google-site-kit-test-plugins,readonly
        # --mount type=bind,source=/home/runner/work/site-kit-wp/site-kit-wp/tests/e2e/mu-plugins,target=/var/www/html/wp-content/mu-plugins,readonly
    steps:
      - uses: actions/checkout@v2
      - name: Import database
        run: docker run -i --rm --volumes-from ${{ job.services.wordpress.id }} --network ${{ job.services.wordpress.network }} wordpress:cli wp db import wp-content/plugins/google-site-kit/bin/local-env/dump.sql
      - name: List posts
        run: docker run -i --rm --volumes-from ${{ job.services.wordpress.id }} --network ${{ job.services.wordpress.network }} wordpress:cli wp post list
