name: WP 4.9

on:
  - push

jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: wordpress_test
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=3
      wordpress:
        image: wordpress:4.9
        ports:
          - 9002:80
        volumes:
          - wordpress_data:/var/www/html
          # - /home/runner/work/site-kit-wp/site-kit-wp/:/var/www/html/wp-content/plugins/google-site-kit
          # - /home/runner/work/site-kit-wp/site-kit-wp/tests/e2e/plugins:/var/www/html/wp-content/plugins/google-site-kit-test-plugins
          # - /home/runner/work/site-kit-wp/site-kit-wp/tests/e2e/mu-plugins:/var/www/html/wp-content/mu-plugins
        env:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_PASSWORD: example
          ABSPATH: /usr/src/wordpress/
          WORDPRESS_DEBUG: 1
          WORDPRESS_CONFIG_EXTRA: |
            define( 'SCRIPT_DEBUG', true );
        options: >-
          --mount type=bind,source="$(pwd)",target=/var/www/html/wp-content/plugins/google-site-kit,readonly
      cli:
        image: wordpress:cli
        volumes:
          - wordpress_data:/var/www/html
          # - /home/runner/work/site-kit-wp/site-kit-wp/:/var/www/html/wp-content/plugins/google-site-kit
          # - /home/runner/work/site-kit-wp/site-kit-wp/tests/e2e/mu-plugins:/var/www/html/wp-content/mu-plugins
        options: >-
          --mount type=bind,source="$(pwd)",target=/var/www/html/wp-content/plugins/google-site-kit,readonly
    steps:
      - uses: actions/checkout@v2
      - name: PWD
        run: echo $PWD
      - name: LS
        run: ls -l .
      - name: Version
        run: docker exec cli wp core version --extra
