name: Plugin Zip Files

on:
  push:
    branches:
      - develop
      - master
    tags: ['**']
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build-zips:
    name: Build Zips
    runs-on: ubuntu-latest
    if: false == ( ( github.event_name == 'pull_request' && ( github.event.action == 'closed' || github.event.pull_request.draft == true ) ) || github.event.pull_request.head.repo.fork )
    steps:
      - uses: actions/checkout@v2
      - name: Load Composer cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          path: ~/.cache/composer/files
      - name: Composer Install
        uses: php-actions/composer@v4
        with:
          dev: no
          php_version: 7.3
      - name: Load NPM cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
      - name: Install NPM dependencies
        uses: ./.github/actions/npm
      - name: Create archives
        run: |
          mkdir -p ${{ github.ref }}
          sudo chown -R $(id -u):$(id -g) .
          npm run dev-zip
          mv *.zip ${{ github.ref }}/google-site-kit-dev.zip
          npm run release-zip
          mv *.zip ${{ github.ref }}/google-site-kit.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: zip-files
          path: ${{ github.ref }}

  deploy-to-wiki:
    name: Deploy To Wiki
    runs-on: ubuntu-20.04
    needs: build-zips
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          ref: master
          token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: zip-files
          path: ${{ github.ref }}
      - name: Commit updates
        run: |
          git add .
          git status
          git diff --staged --quiet && echo 'No changes to commit; exiting!' && exit 0
          git pull --no-edit --quiet
          git commit -m "Build and publish ${{ github.ref }}"
          git push origin master
        env:
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}

  remove-pr:
    name: Remove Zips
    runs-on: ubuntu-20.04
    if: ( github.event_name == 'pull_request' && github.event.action == 'closed' ) && github.event.pull_request.head.repo.fork == false
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          ref: master
          token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
      - name: Prune PR files
        run: |
          rm -rf "refs/pull/${{ github.event.pull_request.number }}"
          git add .
          git status
          git diff --staged --quiet && echo 'No changes to commit; exiting!' && exit 0
          git pull --no-edit --quiet
          git commit -m "Prune refs/pull/${{ github.event.pull_request.number }}"
          git push origin master
        env:
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
